[package]
name = "localton-load-test"
description = "Acton workload generator for the localton network"
version = "0.1.0"
license = "MIT"

[contracts.RecursiveDeployer]
display-name = "Recursive deployer"
src = "contracts/RecursiveDeployer.tolk"
depends = []

[test]

[networks.localnet]
api.v2 = "http://127.0.0.1:3015/api/v1/environments/environment-4/rpc/api/v2"
api.v3 = "http://127.0.0.1:3015/api/v1/environments/environment-4/rpc/api/v3"
explorer = "http://127.0.0.1:3015/virtual-environments/environment-4/explorer"

[fmt]
width = 100
ignore = []

[scripts]
build-root-message = "acton script scripts/build-root-message.tolk"
recursive-load = "acton script scripts/deploy.tolk"

[import-mappings]
acton = ".acton"
contracts = "contracts"
gen = "gen"
tests = "tests"
wrappers = "wrappers"

# Check full Acton.toml reference and all available keys:
# https://ton-blockchain.github.io/acton/docs/acton-toml
