[package]
name = "ton-indexer-p2p"
description = "TON P2P block source for ton-indexer-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
ton-indexer-core = { path = "../ton-indexer-core" }
ton-indexer-liteserver = { path = "../ton-indexer-liteserver" }
ton-p2p = { path = "../ton-p2p" }
tracing.workspace = true

[lints]
workspace = true

[lib]
test = false
doctest = false
