*

!package.json
!bun.lock

!apps/
apps/*
!apps/faucet/
apps/faucet/*
!apps/faucet/Cargo.toml
!apps/faucet/Cargo.lock
!apps/faucet/rust-toolchain.toml
!apps/faucet/build.rs
!apps/faucet/build/
!apps/faucet/build/.env.production
!apps/faucet/src/
!apps/faucet/crates/

!packages/
packages/*
!packages/*/
packages/*/*
!packages/*/package.json
!packages/ui/**
packages/ui/node_modules/
!packages/faucet-ui/**
packages/faucet-ui/node_modules/
packages/faucet-ui/dist/
